#!/bin/bash

# mysql-kill-query: Kill MySQL queries that execution time is above the time 
# (in seconds) specified by command line arguments.)

# Copyright (C) 2013 Carlos Perez Cerrato <cperezcerrato@gmail.com> 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Functions and variables
MYSQL_BIN=""       # Path to MySQL binary command. If not set, 
                                  # fill with 'which mysql'
MYSQL_OPTS=""       # Optional, params of mysql command.

function usage(){
    USE="
Kill MySQL queries that execution time is above the time (in seconds) specified 
by command line arguments.

mysql-kill [ -p PATTERN ] [ -t TIME(in seconds) ] [-l /path/to/file.log ].

    -p  PATTERN (optional) Find PATTERN in MySQL queries.
    -t  TIME (optional) time in seconds, default 15.
    -i  ID (optional) Query ID to kill (specifying -p or -t is not needed using 
        this).
    -l  logfile (optional) File to log killed queries.

Examples:

Kill all queries that contains "exampledb"
$ mysql-kill -p exampledb

Kill all queries that contains "exampledb" and execution time is greater than 
40 seconds and log in file /tmp/mysql-killed.log
$ mysql-kill -p exampledb -t 40 -l /tmp/mysql-killed.log

Kill all queries whose execution time highter 15 seconds (default)
$ mysql-kill

Kill all queries whose execution time is greater than 3 seconds:
$ mysql-kill -t 3

Kill query with id equal to XXXX:
$ mysql-kill -i XXXX
"
echo -e $USE
}

#set -x
function auth(){
    if [ -f $HOME/.mysql-kill-query ];then
        echo "Using stored credentials."
        . $HOME/.mysql-kill-query
    else
        echo -ne "Mysql user: "
        read USER
        echo -ne "Mysql password: "
        read -s PASS
        echo -ne "\nYou want to store credentials in file \
            $HOME/.mysql-kill-query?[y|n]: "
        read OPT
        OPT=${OPT,,}
        while [[ $OPT != "y" && $OPT != "n" ]];do
            echo -en "Invalid option, please insert 'y' (yes) or 'n' (no):"
            read OPT
            OPT=${OPT,,}
        done
        if [ $OPT = "y" ];then
            echo -e "USER=$USER\nPASS=$PASS" > $HOME/.mysql-kill-query ||
                echo "FAIL, user/password not stored."
        fi
    fi
}


function check_var(){
    if [ -z "$USER" ] || [ -z "$PASS" ];then
        echo "You must set USER and PASS in $0."
        exit 1
    elif [ -z "$MYSQL_BIN" ];then
        MYSQL_BIN=$(which mysql)
    fi

    if [ -z $MYSQL_BIN ];then
        echo "I can't find MySQL path."
        exit 1
    else
        MYSQL="$MYSQL_BIN $MYSQL_OPTS -u $USER -p$PASS"
    fi
}

# Main

if [ $# -eq 0 ]; then
    usage
    exit 0
fi

auth
check_var

while getopts "ht:i:p:l:" opt; do
  case $opt in
    t) seconds="$OPTARG" ;;
    p) pattern="$OPTARG" ;;
    l) logfile="$OPTARG" ;;
    i) id="$OPTARG" ;;
    h|?|*) usage && exit 0 ;;
  esac
done

if [ -n "$id" ];then
    pattern="^$id"
    seconds="0"
fi

test -z "$seconds" && seconds=15

if [ -z "$logfile" ];then
    for id in $($MYSQL -B -N -e "SHOW FULL PROCESSLIST;"| \
        awk "/$pattern/{if(\$6 > $seconds){ print \$1}}")
    do
         $MYSQL -B -N -e "KILL $id;" && echo -e "Killing query ID \
             \e[01;31m$id\e[00m"
    done
else
    for id in $($MYSQL -B -N -e "SHOW FULL PROCESSLIST;"| \
        awk "/$pattern/{if(\$6 > $seconds){print \$0 >> \
        \"$logfile\"; print \$1;}}")
    do
         $MYSQL -B -N -e "KILL $id;" && echo -e "Killing query ID \
             \e[01;31m$id\e[00m"
    done
fi

